#!/usr/bin/env python3
"""
validate_coverage_ledger.py - Zero-dependency Python validator for coverage-ledger.json

Validates coverage-ledger.json generated by security-audit against structural,
schema, and security constraints without requiring Node.js.

Usage:
    python validate_coverage_ledger.py <path-to-coverage-ledger.json>
"""

import sys
import os
import json

MAX_FILE_BYTES = 5 * 1024 * 1024  # 5MB limit
VALID_STATES = {"planned", "candidate", "confirmed", "rejected", "blocked"}


def validate_coverage_ledger(file_path):
    if not os.path.exists(file_path):
        print(f"Error: File not found: {file_path}", file=sys.stderr)
        return 1

    file_size = os.path.getsize(file_path)
    if file_size > MAX_FILE_BYTES:
        print(f"Error: File exceeds {MAX_FILE_BYTES} bytes limit (size: {file_size})", file=sys.stderr)
        return 1

    try:
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except UnicodeDecodeError as e:
        print(f"Error: Invalid UTF-8 encoding in coverage ledger JSON: {e}", file=sys.stderr)
        return 1
    except json.JSONDecodeError as e:
        print(f"Error: Failed to parse coverage ledger JSON: {e}", file=sys.stderr)
        return 1

    if not isinstance(data, list):
        print("Error: Root element of coverage-ledger.json must be a JSON array", file=sys.stderr)
        return 1

    errors = []
    seen_ids = set()
    prev_id = ""

    for idx, item in enumerate(data):
        prefix = f"ledger[{idx}]"
        if not isinstance(item, dict):
            errors.append(f"{prefix}: Item must be a JSON object")
            continue

        cov_id = item.get("coverage_id")
        if not cov_id or not isinstance(cov_id, str):
            errors.append(f"{prefix}.coverage_id: Missing or non-string coverage_id")
        else:
            if cov_id in seen_ids:
                errors.append(f"{prefix}.coverage_id: Duplicate coverage_id '{cov_id}'")
            seen_ids.add(cov_id)
            if prev_id and cov_id < prev_id:
                errors.append(f"{prefix}.coverage_id: Units must be sorted lexicographically by coverage_id ('{cov_id}' < '{prev_id}')")
            prev_id = cov_id

        # Required fields for each coverage unit
        for req in ["canonical_refs", "surface", "boundary", "subsystem", "state"]:
            if req not in item:
                errors.append(f"{prefix}: Unit missing required field '{req}'")

        state = item.get("state")
        if state and state not in VALID_STATES:
            errors.append(f"{prefix}.state: Invalid state '{state}', must be one of {list(VALID_STATES)}")

    if errors:
        print(f"Validation failed with {len(errors)} error(s):", file=sys.stderr)
        for err in errors[:50]:
            print(f"  - {err}", file=sys.stderr)
        if len(errors) > 50:
            print(f"  ... and {len(errors) - 50} more errors", file=sys.stderr)
        return 1

    print(f"Successfully validated {len(data)} coverage units in '{file_path}'.")
    return 0


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python validate_coverage_ledger.py <path-to-coverage-ledger.json>", file=sys.stderr)
        sys.exit(1)
    sys.exit(validate_coverage_ledger(sys.argv[1]))
