#!/usr/bin/env python3
"""
validate_findings.py - Zero-dependency Python validator for findings.json

Validates findings.json generated by security-audit against structural,
schema, and security constraints without requiring Node.js.

Usage:
    python validate_findings.py <path-to-findings.json>
"""

import sys
import os
import json
import re

SEVERITY_RANKS = {
    "informational": 0,
    "low": 1,
    "medium": 2,
    "high": 3,
    "critical": 4,
}

MAX_FILE_BYTES = 5 * 1024 * 1024  # 5MB limit
VALID_VERDICTS = {"confirmed", "needs_validation", "rejected"}


def validate_findings(file_path):
    if not os.path.exists(file_path):
        print(f"Error: File not found: {file_path}", file=sys.stderr)
        return 1

    # Check size
    file_size = os.path.getsize(file_path)
    if file_size > MAX_FILE_BYTES:
        print(f"Error: File exceeds {MAX_FILE_BYTES} bytes limit (size: {file_size})", file=sys.stderr)
        return 1

    try:
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except UnicodeDecodeError as e:
        print(f"Error: Invalid UTF-8 encoding in findings JSON: {e}", file=sys.stderr)
        return 1
    except json.JSONDecodeError as e:
        print(f"Error: Failed to parse findings JSON: {e}", file=sys.stderr)
        return 1

    if not isinstance(data, list):
        print("Error: Root element of findings.json must be a JSON array", file=sys.stderr)
        return 1

    errors = []
    seen_fingerprints = set()
    prev_fingerprint = ""

    for idx, item in enumerate(data):
        prefix = f"findings[{idx}]"
        if not isinstance(item, dict):
            errors.append(f"{prefix}: Item must be a JSON object")
            continue

        verdict = item.get("verdict")
        if verdict not in VALID_VERDICTS:
            errors.append(f"{prefix}.verdict: Invalid verdict '{verdict}', must be one of {list(VALID_VERDICTS)}")

        fp = item.get("fingerprint")
        if not fp or not isinstance(fp, str):
            errors.append(f"{prefix}.fingerprint: Missing or non-string fingerprint")
        else:
            if fp in seen_fingerprints:
                errors.append(f"{prefix}.fingerprint: Duplicate fingerprint '{fp}'")
            seen_fingerprints.add(fp)
            if prev_fingerprint and fp < prev_fingerprint:
                errors.append(f"{prefix}.fingerprint: Findings must be sorted lexicographically by fingerprint ('{fp}' < '{prev_fingerprint}')")
            prev_fingerprint = fp

        # Required fields for confirmed findings
        if verdict == "confirmed":
            for req in ["title", "description", "root_cause", "intended_behavior", "trace", "evidence"]:
                if req not in item:
                    errors.append(f"{prefix}: Confirmed finding missing required field '{req}'")

            trace = item.get("trace", [])
            if not isinstance(trace, list) or len(trace) == 0:
                errors.append(f"{prefix}.trace: Must contain at least one trace entry")
            else:
                for t_idx, step in enumerate(trace):
                    if not isinstance(step, dict):
                        errors.append(f"{prefix}.trace[{t_idx}]: Must be an object")
                    elif not step.get("file") or not step.get("line"):
                        errors.append(f"{prefix}.trace[{t_idx}]: Missing file or line number")

            severity = item.get("severity")
            if severity and severity not in SEVERITY_RANKS:
                errors.append(f"{prefix}.severity: Unknown severity '{severity}'")

    if errors:
        print(f"Validation failed with {len(errors)} error(s):", file=sys.stderr)
        for err in errors[:50]:
            print(f"  - {err}", file=sys.stderr)
        if len(errors) > 50:
            print(f"  ... and {len(errors) - 50} more errors", file=sys.stderr)
        return 1

    print(f"Successfully validated {len(data)} findings in '{file_path}'.")
    return 0


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python validate_findings.py <path-to-findings.json>", file=sys.stderr)
        sys.exit(1)
    sys.exit(validate_findings(sys.argv[1]))
